export BELLMAN_NO_GPU=0
export BELLMAN_VERIFIER=gpu
export BELLMAN_CPU_UTILIZATION=0
#export RAYON_NUM_THREADS=6
#export EC_GPU_NUM_THREADS=5000
export BELLMAN_GPU_FRAMEWORK=cuda
#export BELLMAN_CUDA_NVCC_ARGS
#export BELLPERSON_GPUS_PER_LOCK